name: Check SPARQL queries
permissions:
  contents: read
on: [push, pull_request, workflow_call, workflow_dispatch]

jobs:

  check:
    name: Run SPARQL checks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        persist-credentials: false

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install tester
      run: wget "https://github.com/sib-swiss/sparql-examples-utils/releases/download/v2.0.19/sparql-examples-utils-2.0.19-uber.jar" -O sparql-examples-utils.jar

    - name: Run tests
      run: java -jar sparql-examples-utils.jar test --input-directory=examples/
